name: 'POST API Call Action'
description: 'Send a POST request'
author: 'Derek Kershner'
branding:
  icon: 'bell'  
  color: 'yellow'
inputs:
  url:
    description: 'URL to send post request to'
    required: true
  data:
    description: 'JSON string of data to pass into request'
    default: '{}'
    required: false
runs:
  using: 'node12'
  main: 'lib/main.js'